apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  ## remove replica if use HPA
  # replicas: 3  # Scaling the app to 3 replicas
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: risqiikhsani/simple-flask:latest
        resources:
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: flask-app-config
        - secretRef:
            name: flask-app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
