apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}  # The name of the Deployment to scale
  minReplicas: {{ .Values.autoscaling.minReplicas }}  # Minimum number of pods
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}  # Maximum number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}  # Target CPU utilization percentage
